sudo: false
language: node_js
node_js:
    - stable
    - '0.12'
install:
    - npm install
    - npm install -g mocha
    - npm install -g gulp
before_script:
    - npm prune
after_success:
    - npm run semantic-release
branches:
    except:
        - /^v\d+\.\d+\.\d+$/
cache:
    directories:
        - node_modules