sudo: false
language: node_js
node_js:
    - stable
    - '0.12'
install:
    - export NODE_PATH=$(which npm);
    - npm install
    - npm install -g mocha
    - npm install -g gulp
cache:
  directories:
    - node_modules
git:
  depth: 1
